meta_title: "BlockMemo - A place to discover and learn about Cryptocurrencies"
meta_description: "BlockMemo is an educative platform aiming to help any individual interested in having a deeper knowledge about Cryptocurrencies. No regard to the level, we can help you anyway !"
meta_image: "favicon.png" # should exist in `app/assets/images/`
meta_type: "website"
meta_url: "http://blockmemo.co"